package com.gt.model;
// Generated 2015-9-26 12:23:35 by Hibernate Tools 4.0.0

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Integer id;
	private String login;
	private String name;
	private String pass;

	public Account() {
	}

	public Account(String login, String name, String pass) {
		this.login = login;
		this.name = name;
		this.pass = pass;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

}
