package com.gt.model;
// Generated 2015-9-26 12:23:35 by Hibernate Tools 4.0.0

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String type;
	private Boolean hot;


	public Category() {
	}

	public Category(String type, Boolean hot) {
		this.type = type;
		this.hot = hot;
	
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Boolean getHot() {
		return this.hot;
	}

	public void setHot(Boolean hot) {
		this.hot = hot;
	}

}
