package com.gt.model;
// Generated 2015-10-11 20:55:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Sorder generated by hbm2java
 */
public class Sorder implements java.io.Serializable {

	private Integer id;
	private String name;
	private BigDecimal price;
	private Integer number;
	private Integer pid;
	private Integer bid;

	public Sorder() {
	}

	public Sorder(String name, BigDecimal price, Integer number, Integer pid, Integer bid) {
		this.name = name;
		this.price = price;
		this.number = number;
		this.pid = pid;
		this.bid = bid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

}
